[package]
name = "hyprwpe-render"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hyprwpe-core = { workspace = true }
smithay-client-toolkit = { workspace = true }
wayland-client = { workspace = true }
image = { workspace = true }
anyhow = { workspace = true }
