[package]
name = "hyprwpe-render"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hyprwpe-core = { workspace = true }
smithay-client-toolkit = { workspace = true }
wayland-client = { workspace = true }
khronos-egl = { workspace = true }
wayland-egl = { workspace = true }
glow = { workspace = true }
libmpv-sys = { workspace = true }
libloading = { workspace = true }
image = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
