[package]
name = "hyprwpe"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "hyprwpe"
path = "src/main.rs"

[dependencies]
hyprwpe-core = { workspace = true }
clap = { workspace = true }
hyprwpe-render = { workspace = true }
smithay-client-toolkit = { workspace = true }
wayland-client = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
